---
- name: wait until srx boots
  wait_for:
    port: 22
    host: "{{vsrx_ip}}"
    delay: 5
    timeout: 480

- name: create vsrx config
  template: src=templates/{{function}}_config.j2 dest=/tmp/{{function}}.cfg

- name: apply new configuration for role {{function}} on vSRX
  junos_config:
    src: /tmp/{{function}}.cfg
    update: merge
    comment: aply {{function}} configuration
    provider:
      host: "{{vsrx_ip}}"
      username: "{{vsrx_user}}"
      password: "{{vsrx_password}}
