---
- name: check that IP address is given
  fail: msg="vsrx_ip must be defined"
  when: not vsrx_ip is defined

- name: check that username is given
  fail: msg="vsrx_user must be defined"
  when: not vsrx_user is define

- name: check that password is given
  fail: msg="vsrx_password must be defined"
  when: not vsrx_password is define

- name: wait until srx boots
  wait_for:
    port: 22
    host: "{{vsrx_ip}}"
    delay: 5
    timeout: 480

- name: create vsrx config
  template: src=templates/{{function}}_config.j2 dest=/tmp/{{function}}.cfg

- name: apply new configuration for role {{function}} on vSRX
  junos_config:
    src: /tmp/{{function}}.cfg
    update: merge
    comment: aply {{function}} configuration
    provider:
      host: "{{vsrx_ip}}"
      username: "{{vsrx_user}}"
      password: "{{vsrx_password}}"
