---
 - name: update openstack vsrx
   hosts: localhost
   connection: local
   gather_facts: no
   tasks:
   - name: create vsrx config
     template: src=../templates/config.j2 dest=../templates/base_config.j2

   - name: download MechID SSH public key
     get_url: dest=~/tmp/id_rsa.pub.{{rev}} url={{mechid_publickey_url}}

   - name: display groups
     debug: var=groups

   - name: wait unstill srx boots
     wait_for:
       port: 22
       host: "{{srx_mgmntip}}"
       delay: 60
       timeout: 480


 - name: configuration of new user admin on the srx
   hosts: localhost
   connection: local
   gather_facts: no
   tasks:
   - name: set fact
     set_fact: mykey={{ lookup('file', '~/tmp/id_rsa.pub.' + rev) }}

   - name: display key
     debug: var=mykey

   - name: create admin user with ssh key
     junos_user:
       name: "{{mechid}}"
       full_name: "Ansible and Automation MechID"
       role: super-user
       sshkey: "{{ lookup('file', '~/tmp/id_rsa.pub.' + rev) }}"
       state: present
       provider:
         host: "{{srx_mgmntip}}"
         username: "{{srx_user}}"
         password: "{{srx_pass}}"
         
   - name: add additional ssh keys to admin user
     junos_user:
       name: "{{mechid}}"
       full_name: "Ansible and Automation MechID"
       role: super-user
       sshkey: "{{item}}"
       state: present
       provider:
         host: "{{srx_mgmntip}}"
         username: "{{srx_user}}"
         password: "{{srx_pass}}"
     with_items:
       - "{{mechid_sshkeys}}"

   - name: update existing config
     junos_config:
       src: "{{ ../templates/base_config.j2 }}"
       update: merge
       comment:  update existing config by ansible
       provider:
         host: "{{srx_mgmntip}}"
         username: "{{srx_user}}"
         password: "{{srx_pass}}"

# This is removed for demo purposes
# Please uncomment once it is production
#   - name: delete vSRX instance
#     os_server:
#       state: absent
#       name: "{{ srx_hostname }}{{rev}}"
#       wait: yes
#     environment:
#        OS_USERNAME: "{{OSUSERNAME}}"
#        OS_PASSWORD: "{{OSPASSWORD}}"
#        OS_AUTH_URL: "{{OSAUTHURL}}"
#        OS_PROJECT_NAME: "{{OSPROJECTNAME}}"

