---
 - name: deploy openstack vsrx
   hosts: localhost
   connection: local
   gather_facts: no
   tasks:
   - name: deploy vsrx instance
     os_server:
       state: present
       name: "{{ srx_hostname_deploy }}{{rev}}"
       wait: yes
       availability_zone: nova
       image: "{{srx_hostname}}{{rev}}-image"
       flavor: "{{ flavor_name }}"
       security_groups: default
       nics:
         - net-name: "{{left_network}}"
         - net-name: "{{right_network}}"
         - net-name: "{{mgmnt_network}}"
       userdata: "{{lookup('file','../templates/base_config.j2')| string}}"
     environment:
        OS_USERNAME: "{{OSUSERNAME}}"
        OS_PASSWORD: "{{OSPASSWORD}}"
        OS_AUTH_URL: "{{OSAUTHURL}}"
        OS_PROJECT_NAME: "{{OSPROJECTNAME}}"
     register: vm

   - name: get info about the networks
     os_networks_facts:
       filters:
         name: "{{mgmnt_network}}"
     environment:
        OS_USERNAME: "{{OSUSERNAME}}"
        OS_PASSWORD: "{{OSPASSWORD}}"
        OS_AUTH_URL: "{{OSAUTHURL}}"
        OS_PROJECT_NAME: "{{OSPROJECTNAME}}"

   - name: get port facts
     os_port_facts:
       filters:
         device_id: "{{vm.openstack.id}}"
         network_id: "{{openstack_networks[0].id}}"
     environment:
        OS_USERNAME: "{{OSUSERNAME}}"
        OS_PASSWORD: "{{OSPASSWORD}}"
        OS_AUTH_URL: "{{OSAUTHURL}}"
        OS_PROJECT_NAME: "{{OSPROJECTNAME}}"

# This config will be pushed during provisioning 
   - name: create vsrx config
     template: src=../templates/deploy_base_config.j2 dest=../templates/deploy_config.j2

   - name: wait until srx boots
     wait_for:
       port: 22
       host: "{{openstack_ports[0].fixed_ips[0].ip_address}}"
       delay: 60
       timeout: 480

# This tasks tries to deploy a production config to verify that it will work in prod
   - name: deploy a production ready config to vSRX instance
     junos_config:
       src: "{{openstack_ports[0].fixed_ips[0].ip_address}}"
       update: merge
       comment:  update existing config by ansible
       provider:
         host: "{{srx_mgmntip}}"
         username: "{{srx_user}}"
         password: "{{srx_pass}}"

