---
#
# This playbook provision vSRX configuration
# This expects IP address of running vSRX instance
# Variables
#  - vsrx_ip - IP address of running vSRX instance
#  - vsrx_user - user which will be used for connection
#  - vsrx_password - password which will be usedf for connection
# Usage:
# ansible-playbook -e vsrx_ip=10.13.84.55 -e vsrx_user=root -e vsrx_password=Juniper123 provisioning.yml
#

 - name: provisioning vsrx configuration
   hosts: localhost
   connection: local
   gather_facts: no
   roles:
    -  { role: vsrx_provisioning, vsrx_ip: "{{vsrx_ip}}", vsrx_user: "{{vsrx_user}}", vsrx_password: "{{vsrx_password}}", vsrx_sshkeyfile: "{{vsrx_sshkeyfile}}" }
